### ISSUE TITLE
Matrix seems to confuse action-slack...

### ISSUE THREAD

**Issue by FonsRademakers** [8398a7/action-slack#86] opened 2020-06-29 14:25 UTC
For a workflow using a matrix like:

build:
    strategy:
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04]
    runs-on: ${{ matrix.os }}

I get the fields AS_JOB and AS_TOOK undefined. See attached screenshot. Without matrix it all works fine.

![Screen Shot 2020-06-29 at 10 05 20](https://user-images.githubusercontent.com/2265419/86017969-004faf80-ba25-11ea-9d40-e26682d7ed43.png)

**Comment by 8398a7** [comment] 2020-06-30 04:11
Thanks for the report.
The specific repositories were noted, which helped me to find the cause of the problem.

Currently action-slack does not know what items are specified via matrix.
You will need to add one more key to yaml to solve this problem.
The problem itself isn't too difficult to solve and will be addressed in the near future.

Current projections.

```yaml
steps:
  - uses: 8398a7/action-slack@v3
    with:
      status: ...
      fields: ...
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      MATRIX_CONTEXT: ${{ toJson(matrix) }} # Required when using matrix
    if: always()
```

**Comment by FonsRademakers** [comment] 2020-06-30 13:28
I’ve added the:

MATRIX_CONTEXT: ${{ toJson(matrix) }} # Required when using matrix

key for my Ubuntu matrix builds but no change. Do I have to wait for your back-end fix?

Cheers, Fons.



> On 30 Jun 2020, at 06:11, 839 <notifications@github.com> wrote:
> 
> 
> Thanks for the report.
> The specific repositories were noted, which helped me to find the cause of the problem.
> 
> Currently action-slack does not know what items are specified via matrix.
> You will need to add one more key to yaml to solve this problem.
> The problem itself isn't too difficult to solve and will be addressed in the near future.
> 
> Current projections.
> 
> steps
> :
>   - 
> uses: 8398a7/action-slack@v3
> 
>     
> with
> :
>       
> status: ...
> 
>       
> fields: ...
> 
>     
> env
> :
>       
> GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
> 
>       
> SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
> 
>       
> MATRIX_CONTEXT: ${{ toJson(matrix) }} # Required when using matrix
> 
>     
> if: always()
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> 

--------------------------------------------------------------------------
Dr. Fons Rademakers      CERN - European Organization for Nuclear Research
Chief Research Officer   1211 Geneve 23, Switzerland
CERN openlab             Tel: +41227679248            Mobile: +41754113742
--------------------------------------------------------------------------

**Comment by 8398a7** [comment] 2020-06-30 13:54
Until this issue is closed, it is not supported.

**Closed** 2020-07-05 06:12 UTC
